"""Hedging P&L accounting, shared by every strategy (the trained deep
hedge, the Black-Scholes delta baseline, and a trivial "never hedge"
baseline). Having ONE function that turns a sequence of hedge ratios
into a loss number means every strategy is scored by literally the
same code path -- no risk of the comparison being biased by
subtly-different accounting between strategies.

Convention
----------
We model a market-maker who has SOLD one European call (strike K,
maturity T_mat) and dynamically hedges the exposure by trading the
underlying at `n_steps` equally spaced dates. `deltas[:, t]` is the
hedge ratio (number of shares held) held from date t to date t+1, for
t = 0 .. n_steps-1. Position is closed out at maturity (a final trade
back to zero, itself subject to transaction costs).

Loss_i = payoff_i - wealth_i

where `wealth_i` is the cumulative cash generated by the trading
program (negative when buying, positive when selling, minus
proportional transaction costs). Loss is what the option seller has
to cover out of pocket beyond the hedge's trading gains; a smaller
(or more negative) Loss is better. No premium is included here -- see
`deephedge.risk` for how the entropic risk measure of Loss is turned
into an indifference price.

Simplification made explicitly: the cash account does not accrue
interest between rebalancing dates (no discounting of interim cash
flows). See README "Known limitations".
"""
from __future__ import annotations

import numpy as np


def simulate_hedge_loss(paths: np.ndarray, deltas: np.ndarray, K: float,
                         cost_rate: float, return_details: bool = False):
    """paths: (N, n_steps+1). deltas: (N, n_steps). Returns Loss: (N,)
    (or a dict with diagnostics if return_details=True)."""
    N, n_steps_p1 = paths.shape
    n_steps = n_steps_p1 - 1
    assert deltas.shape == (N, n_steps), (deltas.shape, (N, n_steps))

    prev = np.zeros(N)
    wealth = np.zeros(N)
    total_cost = np.zeros(N)
    total_turnover = np.zeros(N)
    for t in range(n_steps):
        d = deltas[:, t]
        trade = d - prev
        S_t = paths[:, t]
        cost = cost_rate * np.abs(trade) * S_t
        cash = -trade * S_t - cost
        wealth += cash
        total_cost += cost
        total_turnover += np.abs(trade)
        prev = d

    S_T = paths[:, n_steps]
    trade = -prev
    cost = cost_rate * np.abs(trade) * S_T
    cash = -trade * S_T - cost
    wealth += cash
    total_cost += cost
    total_turnover += np.abs(trade)

    payoff = np.maximum(S_T - K, 0.0)
    loss = payoff - wealth

    if not return_details:
        return loss
    return {
        "loss": loss,
        "wealth": wealth,
        "payoff": payoff,
        "total_cost": total_cost,
        "total_turnover": total_turnover,
    }
